import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { LivenessDataProvider } from "./components/liveness-data-context";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${GeistSans.variable}`}>
			<body className="mx-auto max-w-5xl py-20">
				<TRPCReactProvider>
					<LivenessDataProvider>{children}</LivenessDataProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
